# Generated by Django 3.2 on 2021-05-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_comments_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время добавления/обновления'),
        ),
    ]
